name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # install your package if using setup.py/pyproject.toml
          pip install pytest

      - name: Run pytest (allow no tests)
        run: |
          pytest || exit_code=$?
          if [ "$exit_code" -eq 5 ]; then
            echo "⚠️ No tests were collected — not failing the job."
          else
            exit $exit_code
          fi
